version: '3.1'
services:
  db:
    image: postgres:alpine
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: words
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data:rw